CREATE USER IF NOT EXISTS 'Admin'@'%' IDENTIFIED BY 'Admin';
GRANT ALL PRIVILEGES ON blog_futbol.* TO 'Admin'@'%' WITH GRANT OPTION;
FLUSH PRIVILEGES;


CREATE TABLE IF NOT EXISTS futbol (
    id INT AUTO_INCREMENT PRIMARY KEY,
    titulo VARCHAR(255) NOT NULL,
    descripcion TEXT NOT NULL,
    imagen VARCHAR(255),
    autor VARCHAR(100) NOT NULL,
    fecha TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
